#! /bin/bash
clear; tput setaf 115; echo -n "///// "; tput setaf 219; echo -n "4CHAN SEARCH "; tput setaf 115; echo "///// ";
echo;
read -r -p "SELECT (1) SINGLE SCAN (2) PERSISTENT SCAN (3) END SCAN PAGE VISIT: " selection1
echo;
if [ $selection1 = 1 ]
then
clear;
echo;
tput setaf 115; echo -n "///// "; tput setaf 219; echo -n "4CHAN SEARCH "; tput setaf 115; echo "///// ";
echo;
tput setaf 11; echo "SINGLE SCAN";
echo;
tput setaf 9; echo "TYPE 'NULL' FOR EMPTY SEARCHES";
echo "OTHERWISE YOU WILL RECIEVE FULL PAGE RETURNS";
echo;
tput setaf 14; echo "===============BOARD SELECTION===============";
tput setaf 15; read -r -p "ENTER BOARD (EXAMPLE: B): " board1;
tput setaf 14; echo "=============================================";
echo;
echo;
echo "===============SEARCH TERMS (4)==============";
tput setaf 15; read -r -p "ENTER IN SEARCH TERM 1: " term1;
read -r -p "ENTER IN SEARCH TERM 2: " term2;
read -r -p "ENTER IN SEARCH TERM 3: " term3;
read -r -p "ENTER IN SEARCH TERM 4: " term4;
tput setaf 14; echo "=============================================";
echo;
echo;
echo "SCANNING 4CHAN.ORG/$board1/" | lolcat -a -s 999 -d 200;
echo "";
echo "SCANNING 4CHAN.ORG/$board1/1" | lolcat -a -s 999;
echo "NUMBER OF MENTIONS:";
w3m boards.4chan.org/$board1/ | grep -i -E --color=always "$term1|$term2|$term3|$term4" -c;
w3m boards.4chan.org/$board1/ | grep -i -E --color=always "$term1|$term2|$term3|$term4";
echo "";
echo "SCANNING 4CHAN.ORG/$board1/2" | lolcat -a -s 999;
echo "NUMBER OF MENTIONS:";
w3m boards.4chan.org/$board1/2 | grep -i -E --color=always "$term1|$term2|$term3|$term4" -c;
w3m boards.4chan.org/$board1/2 | grep -i -E --color=always "$term1|$term2|$term3|$term4";
echo "";
echo "SCANNING 4CHAN.ORG/$board1/3" | lolcat -a -s 999;
echo "NUMBER OF MENTIONS:";
w3m boards.4chan.org/$board1/3 | grep -i -E --color=always "$term1|$term2|$term3|$term4" -c;
w3m boards.4chan.org/$board1/3 | grep -i -E --color=always "$term1|$term2|$term3|$term4";
echo "";
echo "SCANNING 4CHAN.ORG/$board1/4" | lolcat -a -s 999;
echo "NUMBER OF MENTIONS:";
w3m boards.4chan.org/$board1/4 | grep -i -E --color=always "$term1|$term2|$term3|$term4" -c;
w3m boards.4chan.org/$board1/4 | grep -i -E --color=always "$term1|$term2|$term3|$term4";
echo "";
echo "SCANNING 4CHAN.ORG/$board1/5" | lolcat -a -s 999;
echo "NUMBER OF MENTIONS:";
w3m boards.4chan.org/$board1/5 | grep -i -E --color=always "$term1|$term2|$term3|$term4" -c;
w3m boards.4chan.org/$board1/5 | grep -i -E --color=always "$term1|$term2|$term3|$term4";
echo "";
echo "SCANNING 4CHAN.ORG/$board1/6" | lolcat -a -s 999;
echo "NUMBER OF MENTIONS:";
w3m boards.4chan.org/$board1/6 | grep -i -E --color=always "$term1|$term2|$term3|$term4" -c;
w3m boards.4chan.org/$board1/6 | grep -i -E --color=always "$term1|$term2|$term3|$term4";
echo "";
echo "SCANNING 4CHAN.ORG/$board1/7" | lolcat -a -s 999;
echo "NUMBER OF MENTIONS:";
w3m boards.4chan.org/$board1/7 | grep -i -E --color=always "$term1|$term2|$term3|$term4" -c;
w3m boards.4chan.org/$board1/7 | grep -i -E --color=always "$term1|$term2|$term3|$term4";
echo "";
echo "SCANNING 4CHAN.ORG/$board1/8" | lolcat -a -s 999;
echo "NUMBER OF MENTIONS:";
w3m boards.4chan.org/$board1/8 | grep -i -E --color=always "$term1|$term2|$term3|$term4" -c;
w3m boards.4chan.org/$board1/8 | grep -i -E --color=always "$term1|$term2|$term3|$term4";
echo "";
echo "SCANNING 4CHAN.ORG/$board1/9" | lolcat -a -s 999;
echo "NUMBER OF MENTIONS:";
w3m boards.4chan.org/$board1/9 | grep -i -E --color=always "$term1|$term2|$term3|$term4" -c;
w3m boards.4chan.org/$board1/9 | grep -i -E --color=always "$term1|$term2|$term3|$term4";
echo "";
echo "SCANNING 4CHAN.ORG/$board1/10" | lolcat -a -s 999;
echo "NUMBER OF MENTIONS:";
w3m boards.4chan.org/$board1/10 | grep -i -E --color=always "$term1|$term2|$term3|$term4" -c;
w3m boards.4chan.org/$board1/10 | grep -i -E --color=always "$term1|$term2|$term3|$term4";
echo "";
tput setaf 9; echo "SCAN COMPLETE";
tput setaf 11; echo -n "TIMESTAMP: "; date;
echo "============================================================"; tput setaf 15;
#====================================================RETURN
read -p "WOULD YOU LIKE TO RETURN TO THE MENU? (y/n): " ANSWER;
if [ "$ANSWER" = y ]
then
bash ./4chan.sh;
fi
if [ "$ANSWER" = n ]
then
echo;
fi
fi
if [ $selection1 = 2 ]
then
clear; echo;
tput setaf 115; echo -n "///// "; tput setaf 219; echo -n "4CHAN SEARCH "; tput setaf 115; echo "///// ";
echo;
tput setaf 11; echo "PER PAGE BOARD SEARCH + PERSISTENT SCAN";
echo;
tput setaf 9; echo "TYPE 'NULL' FOR EMPTY SEARCHES";
echo "OTHERWISE YOU WILL RECIEVE FULL PAGE RETURNS";
echo;
tput setaf 14; echo "===============BOARD SELECTION===============";
tput setaf 15; read -r -p "ENTER BOARD (EXAMPLE: B): " board1;
tput setaf 14; echo "=============================================";
echo;
echo;
echo "===============SEARCH TERMS (4)==============";
tput setaf 15; read -r -p "ENTER IN SEARCH TERM 1: " term1;
read -r -p "ENTER IN SEARCH TERM 2: " term2;
read -r -p "ENTER IN SEARCH TERM 3: " term3;
read -r -p "ENTER IN SEARCH TERM 4: " term4;
tput setaf 14; echo "=============================================";
echo;
echo;
echo "==============PERSISTANT SEARCH==============";
tput setaf 15; read -r -p "ENTER IN DELAY FOR REPEAT+LOG (SECONDS): " seconds1;
tput setaf 14; echo "=============================================";
echo;
while true; do echo "SCANNING 4CHAN.ORG/$board1/" | lolcat -a -s 999 -d 300;
echo "";
echo "SCANNING 4CHAN.ORG/$board1/1" | lolcat -a -s 999;
echo "NUMBER OF MENTIONS:";
w3m boards.4chan.org/$board1/ | grep -i -E --color=always "$term1|$term2|$term3|$term4" -c;
w3m boards.4chan.org/$board1/ | grep -i -E --color=always "$term1|$term2|$term3|$term4";
echo "";
echo "SCANNING 4CHAN.ORG/$board1/2" | lolcat -a -s 999;
echo "NUMBER OF MENTIONS:";
w3m boards.4chan.org/$board1/2 | grep -i -E --color=always "$term1|$term2|$term3|$term4" -c;
w3m boards.4chan.org/$board1/2 | grep -i -E --color=always "$term1|$term2|$term3|$term4";
echo "";
echo "SCANNING 4CHAN.ORG/$board1/3" | lolcat -a -s 999;
echo "NUMBER OF MENTIONS:";
w3m boards.4chan.org/$board1/3 | grep -i -E --color=always "$term1|$term2|$term3|$term4" -c;
w3m boards.4chan.org/$board1/3 | grep -i -E --color=always "$term1|$term2|$term3|$term4";
echo "";
echo "SCANNING 4CHAN.ORG/$board1/4" | lolcat -a -s 999;
echo "NUMBER OF MENTIONS:";
w3m boards.4chan.org/$board1/4 | grep -i -E --color=always "$term1|$term2|$term3|$term4" -c;
w3m boards.4chan.org/$board1/4 | grep -i -E --color=always "$term1|$term2|$term3|$term4";
echo "";
echo "SCANNING 4CHAN.ORG/$board1/5" | lolcat -a -s 999;
echo "NUMBER OF MENTIONS:";
w3m boards.4chan.org/$board1/5 | grep -i -E --color=always "$term1|$term2|$term3|$term4" -c;
w3m boards.4chan.org/$board1/5 | grep -i -E --color=always "$term1|$term2|$term3|$term4";
echo "";
echo "SCANNING 4CHAN.ORG/$board1/6" | lolcat -a -s 999;
echo "NUMBER OF MENTIONS:";
w3m boards.4chan.org/$board1/6 | grep -i -E --color=always "$term1|$term2|$term3|$term4" -c;
w3m boards.4chan.org/$board1/6 | grep -i -E --color=always "$term1|$term2|$term3|$term4";
echo "";
echo "SCANNING 4CHAN.ORG/$board1/7" | lolcat -a -s 999;
echo "NUMBER OF MENTIONS:";
w3m boards.4chan.org/$board1/7 | grep -i -E --color=always "$term1|$term2|$term3|$term4" -c;
w3m boards.4chan.org/$board1/7 | grep -i -E --color=always "$term1|$term2|$term3|$term4";
echo "";
echo "SCANNING 4CHAN.ORG/$board1/8" | lolcat -a -s 999;
echo "NUMBER OF MENTIONS:";
w3m boards.4chan.org/$board1/8 | grep -i -E --color=always "$term1|$term2|$term3|$term4" -c;
w3m boards.4chan.org/$board1/8 | grep -i -E --color=always "$term1|$term2|$term3|$term4";
echo "";
echo "SCANNING 4CHAN.ORG/$board1/9" | lolcat -a -s 999;
echo "NUMBER OF MENTIONS:";
w3m boards.4chan.org/$board1/9 | grep -i -E --color=always "$term1|$term2|$term3|$term4" -c;
w3m boards.4chan.org/$board1/9 | grep -i -E --color=always "$term1|$term2|$term3|$term4";
echo "";
echo "SCANNING 4CHAN.ORG/$board1/10" | lolcat -a -s 999;
echo "NUMBER OF MENTIONS:";
w3m boards.4chan.org/$board1/10 | grep -i -E --color=always "$term1|$term2|$term3|$term4" -c;
w3m boards.4chan.org/$board1/10 | grep -i -E --color=always "$term1|$term2|$term3|$term4";
echo "";
tput setaf 9; echo "SCAN COMPLETE";
tput setaf 11; echo -n "TIMESTAMP: "; date;
echo "============================================================"; tput setaf 15;
tput setaf 15; echo "SEARCH WILL REPEAT IN $seconds1 SECONDS";
tput setaf 14; echo "//////////////////////////////////////////////";
sleep $seconds1; done
fi
if [ $selection1 = 3 ]
then
clear;
echo;
tput setaf 115; echo -n "///// "; tput setaf 219; echo -n "4CHAN SEARCH "; tput setaf 115; echo "///// ";
echo;
tput setaf 11; echo "PER PAGE BOARD SEARCH + END SCAN PAGE VISIT";
echo;
tput setaf 9; echo "TYPE 'NULL' FOR EMPTY SEARCHES";
echo "OTHERWISE YOU WILL RECIEVE FULL PAGE RETURNS";
echo;
tput setaf 14; echo "===============BOARD SELECTION===============";
tput setaf 15; read -r -p "ENTER BOARD (EXAMPLE: B): " board1;
tput setaf 14; echo "=============================================";
echo;
echo;
echo "===============SEARCH TERMS (4)==============";
tput setaf 15; read -r -p "ENTER IN SEARCH TERM 1: " term1;
read -r -p "ENTER IN SEARCH TERM 2: " term2;
read -r -p "ENTER IN SEARCH TERM 3: " term3;
read -r -p "ENTER IN SEARCH TERM 4: " term4;
tput setaf 14; echo "=============================================";
echo;
echo;
echo "SCANNING 4CHAN.ORG/$board1/" | lolcat -a -s 999 -d 200;
echo "";
echo "SCANNING 4CHAN.ORG/$board1/1" | lolcat -a -s 999;
echo "NUMBER OF MENTIONS:";
w3m boards.4chan.org/$board1/ | grep -i -E --color=always "$term1|$term2|$term3|$term4" -c;
w3m boards.4chan.org/$board1/ | grep -i -E --color=always "$term1|$term2|$term3|$term4";
echo "";
echo "SCANNING 4CHAN.ORG/$board1/2" | lolcat -a -s 999;
echo "NUMBER OF MENTIONS:";
w3m boards.4chan.org/$board1/2 | grep -i -E --color=always "$term1|$term2|$term3|$term4" -c;
w3m boards.4chan.org/$board1/2 | grep -i -E --color=always "$term1|$term2|$term3|$term4";
echo "";
echo "SCANNING 4CHAN.ORG/$board1/3" | lolcat -a -s 999;
echo "NUMBER OF MENTIONS:";
w3m boards.4chan.org/$board1/3 | grep -i -E --color=always "$term1|$term2|$term3|$term4" -c;
w3m boards.4chan.org/$board1/3 | grep -i -E --color=always "$term1|$term2|$term3|$term4";
echo "";
echo "SCANNING 4CHAN.ORG/$board1/4" | lolcat -a -s 999;
echo "NUMBER OF MENTIONS:";
w3m boards.4chan.org/$board1/4 | grep -i -E --color=always "$term1|$term2|$term3|$term4" -c;
w3m boards.4chan.org/$board1/4 | grep -i -E --color=always "$term1|$term2|$term3|$term4";
echo "";
echo "SCANNING 4CHAN.ORG/$board1/5" | lolcat -a -s 999;
echo "NUMBER OF MENTIONS:";
w3m boards.4chan.org/$board1/5 | grep -i -E --color=always "$term1|$term2|$term3|$term4" -c;
w3m boards.4chan.org/$board1/5 | grep -i -E --color=always "$term1|$term2|$term3|$term4";
echo "";
echo "SCANNING 4CHAN.ORG/$board1/6" | lolcat -a -s 999;
echo "NUMBER OF MENTIONS:";
w3m boards.4chan.org/$board1/6 | grep -i -E --color=always "$term1|$term2|$term3|$term4" -c;
w3m boards.4chan.org/$board1/6 | grep -i -E --color=always "$term1|$term2|$term3|$term4";
echo "";
echo "SCANNING 4CHAN.ORG/$board1/7" | lolcat -a -s 999;
echo "NUMBER OF MENTIONS:";
w3m boards.4chan.org/$board1/7 | grep -i -E --color=always "$term1|$term2|$term3|$term4" -c;
w3m boards.4chan.org/$board1/7 | grep -i -E --color=always "$term1|$term2|$term3|$term4";
echo "";
echo "SCANNING 4CHAN.ORG/$board1/8" | lolcat -a -s 999;
echo "NUMBER OF MENTIONS:";
w3m boards.4chan.org/$board1/8 | grep -i -E --color=always "$term1|$term2|$term3|$term4" -c;
w3m boards.4chan.org/$board1/8 | grep -i -E --color=always "$term1|$term2|$term3|$term4";
echo "";
echo "SCANNING 4CHAN.ORG/$board1/9" | lolcat -a -s 999;
echo "NUMBER OF MENTIONS:";
w3m boards.4chan.org/$board1/9 | grep -i -E --color=always "$term1|$term2|$term3|$term4" -c;
w3m boards.4chan.org/$board1/9 | grep -i -E --color=always "$term1|$term2|$term3|$term4";
echo "";
echo "SCANNING 4CHAN.ORG/$board1/10" | lolcat -a -s 999;
echo "NUMBER OF MENTIONS:";
w3m boards.4chan.org/$board1/10 | grep -i -E --color=always "$term1|$term2|$term3|$term4" -c;
w3m boards.4chan.org/$board1/10 | grep -i -E --color=always "$term1|$term2|$term3|$term4";
echo "";
tput setaf 9; echo "SCAN COMPLETE";
tput setaf 11; echo -n "TIMESTAMP: "; date;
echo "============================================================"; tput setaf 15;
echo;
tput setaf 14; echo "================ENTER IN PAGE================";
tput setaf 15; read -r -p "PAGE TO VISIT (ENTER DEFAULT PAGE ["1"]): " page1;
tput setaf 14; echo "=============================================";
w3m boards.4chan.org/$board1/$page1;
fi
